name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - master

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Installing the library
        shell: bash -l {0}
        run: |
         pip install .
      - name: Build and Commit
        uses: sphinx-notes/pages@v2
        with:
          requirements_path: docs/doc_requirements.txt
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
